using PasswordlessAuthenticationApplication.Samples;
using Xunit;

namespace PasswordlessAuthenticationApplication.EntityFrameworkCore.Applications;

[Collection(PasswordlessAuthenticationApplicationTestConsts.CollectionDefinitionName)]
public class EfCoreSampleAppServiceTests : SampleAppServiceTests<PasswordlessAuthenticationApplicationEntityFrameworkCoreTestModule>
{

}
