using PasswordlessAuthApp.EntityFrameworkCore;
using Xunit;

namespace PasswordlessAuthApp.EntityFrameworkCore;

public class PasswordlessAuthAppEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<PasswordlessAuthAppEntityFrameworkCoreFixture>
{

}
