using Volo.Abp;

namespace PasswordlessAuthenticationApplication.EntityFrameworkCore;

public abstract class PasswordlessAuthenticationApplicationEntityFrameworkCoreTestBase : PasswordlessAuthenticationApplicationTestBase<PasswordlessAuthenticationApplicationEntityFrameworkCoreTestModule>
{

}
