using Xunit;

namespace PasswordlessAuthenticationApplication.EntityFrameworkCore;

[CollectionDefinition(PasswordlessAuthenticationApplicationTestConsts.CollectionDefinitionName)]
public class PasswordlessAuthenticationApplicationEntityFrameworkCoreCollection : ICollectionFixture<PasswordlessAuthenticationApplicationEntityFrameworkCoreFixture>
{

}
